### ISSUE TITLE
OSX

### ISSUE THREAD

**Issue by wamatt** [ajaiantilal/i7z#2]
This looks awesome. Bit of a longshot, but does an OSX port exist?

**Comment by ajaiantilal** [comment]
actually no OSX port.

i think it may be doable (provided i can access an osx machine from somewhere) via the api depicted here http://software.intel.com/en-us/blogs/2012/12/13/using-the-intel-power-gadget-api-on-mac-os-x

**Comment by wamatt** [comment]
:+1:  ta
